# Generated by Django 4.0.5 on 2022-10-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='holes',
            field=models.IntegerField(choices=[(9, 9), (18, 18)], default=18),
            preserve_default=False,
        ),
    ]
