# Generated by Django 4.0.5 on 2022-10-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_user_handicap'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='course_comb',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
