# Generated by Django 4.0.5 on 2022-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_score_course_comb'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date_comb',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='differential_first',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='differential_second',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rating_comb',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='score_comb',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='slope_comb',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
