# Generated by Django 4.0.5 on 2022-12-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='course_comb',
        ),
        migrations.RemoveField(
            model_name='score',
            name='date_comb',
        ),
        migrations.RemoveField(
            model_name='score',
            name='differential_first',
        ),
        migrations.RemoveField(
            model_name='score',
            name='differential_second',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rating_comb',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_comb',
        ),
        migrations.RemoveField(
            model_name='score',
            name='slope_comb',
        ),
    ]
